insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (1, 'Concluido', 'Pepper - White, Whole', 69.5, 79);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (2, 'Em Andamento', 'Island Oasis - Pina Colada', 18.5, 3);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (3, 'Em Andamento', 'Squid - U - 10 Thailand', 50.44, 35);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (4, 'Concluido', 'Cake Circle, Paprus', 38.78, 58);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (5, 'Concluido', 'Wine - Chianti Classica Docg', 88.19, 39);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (6, 'Cancelado', 'Red Currants', 75.81, 26);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (7, 'Concluido', 'Chinese Foods - Thick Noodles', 81.85, 96);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (8, 'Concluido', 'Syrup - Monin, Amaretta', 89.66, 63);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (9, 'Em Andamento', 'Bread - Multigrain, Loaf', 75.51, 79);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (10, 'Concluido', 'Sauce - Soya, Dark', 73.41, 52);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (11, 'Concluido', 'Chocolate - Dark Callets', 80.45, 31);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (12, 'Cancelado', 'Rice - Brown', 28.92, 16);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (13, 'Concluido', 'Cheese - Gorgonzola', 50.62, 46);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (14, 'Cancelado', 'Olives - Stuffed', 34.44, 54);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (15, 'Concluido', 'Onions - Spanish', 84.0, 6);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (16, 'Cancelado', 'Lettuce - Romaine', 40.59, 94);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (17, 'Em Andamento', 'Miso - Soy Bean Paste', 2.09, 78);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (18, 'Concluido', 'Shallots', 89.38, 49);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (19, 'Em Andamento', 'Chocolate - White', 95.34, 69);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (20, 'Concluido', 'Oil - Canola', 94.57, 56);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (21, 'Concluido', 'Wine - Tribal Sauvignon', 23.27, 84);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (22, 'Concluido', 'Wine - Sicilia Igt Nero Avola', 22.28, 20);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (23, 'Concluido', 'Horseradish - Prepared', 1.67, 92);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (24, 'Em Andamento', 'Beans - Wax', 87.22, 59);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (25, 'Cancelado', 'Sponge Cake Mix - Chocolate', 66.02, 6);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (26, 'Concluido', 'Yogurt - Strawberry, 175 Gr', 93.35, 21);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (27, 'Concluido', 'Soup Bowl Clear 8oz92008', 34.12, 5);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (28, 'Em Andamento', 'Crab - Dungeness, Whole, live', 60.39, 18);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (29, 'Concluido', 'Shrimp - Black Tiger 13/15', 26.67, 49);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (30, 'Cancelado', 'Beer - Moosehead', 38.24, 8);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (31, 'Cancelado', 'Papayas', 76.8, 82);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (32, 'Concluido', 'Pears - Anjou', 89.5, 99);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (33, 'Em Andamento', 'Pork - Backs - Boneless', 30.99, 36);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (34, 'Cancelado', 'Boogies', 55.6, 98);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (35, 'Concluido', 'Yogurt - Raspberry, 175 Gr', 77.93, 64);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (36, 'Concluido', 'Juice - Ocean Spray Cranberry', 35.13, 63);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (37, 'Em Andamento', 'Beans - Black Bean, Canned', 48.67, 94);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (38, 'Cancelado', 'Veal - Ground', 59.5, 73);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (39, 'Concluido', 'Bagel - 12 Grain Preslice', 29.74, 35);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (40, 'Concluido', 'Chocolate - Milk', 49.14, 54);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (41, 'Em Andamento', 'Chivas Regal - 12 Year Old', 86.27, 59);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (42, 'Cancelado', 'Veal - Heart', 30.69, 88);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (43, 'Em Andamento', 'Oven Mitt - 13 Inch', 24.66, 45);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (44, 'Cancelado', 'Beef - Baby, Liver', 58.43, 94);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (45, 'Concluido', 'Kahlua', 53.78, 37);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (46, 'Cancelado', 'Tuna - Fresh', 62.25, 21);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (47, 'Cancelado', 'Frangelico', 61.55, 71);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (48, 'Concluido', 'Coriander - Seed', 43.62, 67);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (49, 'Concluido', 'Cookie Dough - Oatmeal Rasin', 13.29, 61);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (50, 'Cancelado', 'Cookies - Fortune', 67.08, 9);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (51, 'Em Andamento', 'Tomatoes - Yellow Hot House', 87.47, 85);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (52, 'Concluido', 'Sandwich Wrap', 42.03, 22);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (53, 'Concluido', 'Beans - Black Bean, Dry', 13.3, 7);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (54, 'Em Andamento', 'Puree - Strawberry', 28.74, 58);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (55, 'Em Andamento', 'Oil - Grapeseed Oil', 5.84, 13);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (56, 'Cancelado', 'Crab - Imitation Flakes', 32.44, 21);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (57, 'Concluido', 'Pastry - Cherry Danish - Mini', 97.44, 30);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (58, 'Em Andamento', 'Wine - White, Colubia Cresh', 63.18, 17);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (59, 'Cancelado', 'Chickensplit Half', 57.2, 57);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (60, 'Em Andamento', 'Mustard - Pommery', 19.32, 64);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (61, 'Concluido', 'Beef - Kobe Striploin', 66.72, 66);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (62, 'Cancelado', 'Pasta - Cannelloni, Sheets, Fresh', 6.51, 49);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (63, 'Concluido', 'Nectarines', 53.69, 88);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (64, 'Concluido', 'Cocktail Napkin Blue', 94.13, 60);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (65, 'Concluido', 'Snapple Lemon Tea', 61.67, 36);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (66, 'Cancelado', 'Wine - Periguita Fonseca', 41.42, 43);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (67, 'Cancelado', 'Lotus Leaves', 43.43, 81);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (68, 'Concluido', 'Wine - Red, Marechal Foch', 33.19, 58);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (69, 'Cancelado', 'Dish Towel', 27.71, 95);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (70, 'Cancelado', 'Chicken - Ground', 44.31, 87);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (71, 'Em Andamento', 'Beans - Black Bean, Canned', 72.14, 56);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (72, 'Cancelado', 'Mushroom - Chanterelle Frozen', 45.22, 75);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (73, 'Em Andamento', 'Brandy Apricot', 98.99, 68);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (74, 'Em Andamento', 'Jam - Apricot', 87.0, 17);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (75, 'Concluido', 'Oil - Sunflower', 40.66, 47);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (76, 'Concluido', 'Bread Roll Foccacia', 24.26, 74);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (77, 'Em Andamento', 'Mustard - Dijon', 26.61, 15);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (78, 'Cancelado', 'Dry Ice', 25.1, 57);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (79, 'Concluido', 'Garbage Bag - Clear', 64.74, 62);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (80, 'Cancelado', 'Soup Knorr Chili With Beans', 59.74, 5);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (81, 'Concluido', 'Vinegar - Balsamic, White', 69.32, 4);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (82, 'Cancelado', 'Alize Sunset', 57.11, 65);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (83, 'Cancelado', 'Filling - Mince Meat', 1.62, 4);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (84, 'Cancelado', 'Wine - Red, Black Opal Shiraz', 82.47, 8);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (85, 'Em Andamento', 'Flour - Teff', 61.16, 24);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (86, 'Concluido', 'Carbonated Water - Lemon Lime', 46.52, 12);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (87, 'Concluido', 'Lamb - Whole, Frozen', 17.72, 100);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (88, 'Em Andamento', 'Salad Dressing', 71.08, 3);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (89, 'Cancelado', 'Cheese - Le Cheve Noir', 46.44, 36);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (90, 'Cancelado', 'Bread - Olive Dinner Roll', 67.97, 3);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (91, 'Concluido', 'Doilies - 12, Paper', 74.4, 24);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (92, 'Em Andamento', 'Cheese - Cheddar, Mild', 45.29, 77);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (93, 'Em Andamento', 'Flour - Masa De Harina Mexican', 92.13, 73);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (94, 'Cancelado', 'Carrots - Jumbo', 4.88, 90);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (95, 'Em Andamento', 'Mustard - Individual Pkg', 31.32, 18);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (96, 'Cancelado', 'Eggplant Italian', 50.11, 22);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (97, 'Concluido', 'Pasta - Shells, Medium, Dry', 24.39, 4);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (98, 'Cancelado', 'Wasabi Powder', 38.31, 36);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (99, 'Em Andamento', 'Oil - Sunflower', 13.68, 9);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (100, 'Cancelado', 'Energy Drink Bawls', 89.14, 61);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (101, 'Cancelado', 'Cornflakes', 25.06, 64);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (102, 'Cancelado', 'Chambord Royal', 71.07, 8);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (103, 'Cancelado', 'Wine - Chardonnay Mondavi', 46.69, 60);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (104, 'Concluido', 'Rum - White, Gg White', 81.21, 68);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (105, 'Em Andamento', 'Walkers Special Old Whiskey', 39.73, 75);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (106, 'Cancelado', 'Lobster - Baby, Boiled', 23.33, 65);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (107, 'Concluido', 'Juice - V8, Tomato', 25.59, 19);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (108, 'Cancelado', 'Muffin Puck Ww Carrot', 32.43, 31);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (109, 'Cancelado', 'Wine - Charddonnay Errazuriz', 65.56, 85);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (110, 'Em Andamento', 'Pork - Bacon, Sliced', 16.42, 65);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (111, 'Cancelado', 'Wine - Sicilia Igt Nero Avola', 1.29, 14);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (112, 'Cancelado', 'Sponge Cake Mix - Chocolate', 63.2, 79);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (113, 'Cancelado', 'Table Cloth 72x144 White', 82.9, 100);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (114, 'Cancelado', 'Doilies - 10, Paper', 58.31, 74);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (115, 'Concluido', 'Sugar - Invert', 99.14, 90);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (116, 'Concluido', 'Bar Mix - Pina Colada, 355 Ml', 27.88, 5);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (117, 'Em Andamento', 'Coffee Cup 12oz 5342cd', 90.59, 25);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (118, 'Concluido', 'Sultanas', 53.85, 19);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (119, 'Em Andamento', 'Horseradish - Prepared', 16.2, 88);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (120, 'Concluido', 'Seedlings - Mix, Organic', 50.42, 95);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (121, 'Cancelado', 'Yogurt - Strawberry, 175 Gr', 45.3, 71);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (122, 'Concluido', 'Gelatine Leaves - Envelopes', 23.05, 25);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (123, 'Cancelado', 'Quail - Jumbo', 90.69, 46);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (124, 'Concluido', 'Grapefruit - White', 54.85, 70);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (125, 'Cancelado', 'Clams - Littleneck, Whole', 76.88, 59);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (126, 'Em Andamento', 'Mushroom - Lg - Cello', 18.97, 5);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (127, 'Em Andamento', 'Sprouts Dikon', 92.87, 9);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (128, 'Cancelado', 'Lid - Translucent, 3.5 And 6 Oz', 81.82, 73);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (129, 'Concluido', 'Schnappes Peppermint - Walker', 56.22, 29);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (130, 'Em Andamento', 'Wine - Shiraz Wolf Blass Premium', 13.89, 70);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (131, 'Concluido', 'Lychee', 78.17, 30);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (132, 'Em Andamento', 'Icecream - Dstk Cml And Fdg', 51.15, 45);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (133, 'Concluido', 'Shrimp - Black Tiger 26/30', 85.78, 6);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (134, 'Cancelado', 'Trueblue - Blueberry 12x473ml', 14.69, 74);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (135, 'Cancelado', 'Mustard Prepared', 99.01, 1);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (136, 'Em Andamento', 'Tomatoes - Vine Ripe, Red', 18.13, 37);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (137, 'Cancelado', 'Asparagus - White, Fresh', 75.92, 6);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (138, 'Em Andamento', 'Grapes - Red', 51.68, 78);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (139, 'Concluido', 'Beer - Original Organic Lager', 44.56, 62);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (140, 'Cancelado', 'Campari', 59.44, 16);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (141, 'Em Andamento', 'Pork - Belly Fresh', 87.18, 14);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (142, 'Cancelado', 'Crab Meat Claw Pasteurise', 67.81, 1);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (143, 'Cancelado', 'Dikon', 3.03, 40);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (144, 'Em Andamento', 'Bread Crumbs - Japanese Style', 69.55, 74);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (145, 'Concluido', 'Squid Ink', 39.86, 41);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (146, 'Concluido', 'Sugar - Brown', 52.12, 93);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (147, 'Cancelado', 'Venison - Striploin', 75.41, 77);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (148, 'Em Andamento', 'Appetizer - Lobster Phyllo Roll', 80.45, 23);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (149, 'Concluido', 'Spice - Chili Powder Mexican', 22.2, 91);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (150, 'Concluido', 'Tart Shells - Savory, 2', 13.86, 87);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (151, 'Cancelado', 'Gelatine Leaves - Bulk', 32.64, 23);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (152, 'Concluido', 'Eggs - Extra Large', 87.48, 75);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (153, 'Cancelado', 'Rosemary - Dry', 67.86, 2);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (154, 'Cancelado', 'Veal - Inside', 7.34, 51);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (155, 'Concluido', 'Soup - Verve - Chipotle Chicken', 89.15, 46);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (156, 'Cancelado', 'Mackerel Whole Fresh', 42.5, 34);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (157, 'Cancelado', 'Chicken - Ground', 67.49, 5);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (158, 'Cancelado', 'Cheese - Cheddar, Medium', 82.2, 66);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (159, 'Cancelado', 'Beer - Sleeman Fine Porter', 59.8, 85);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (160, 'Concluido', 'Steam Pan - Half Size Deep', 25.37, 9);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (161, 'Concluido', 'Appetizer - Southwestern', 23.65, 96);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (162, 'Cancelado', 'Lamb - Bones', 10.91, 91);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (163, 'Concluido', 'Chickensplit Half', 39.4, 100);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (164, 'Concluido', 'Currants', 92.92, 41);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (165, 'Concluido', 'Propel Sport Drink', 96.57, 38);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (166, 'Cancelado', 'Nut - Walnut, Pieces', 81.89, 43);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (167, 'Cancelado', 'Taro Leaves', 91.07, 64);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (168, 'Concluido', 'Soup - French Can Pea', 17.57, 3);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (169, 'Concluido', 'Salami - Genova', 97.25, 54);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (170, 'Concluido', 'Wine - Cava Aria Estate Brut', 10.15, 45);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (171, 'Em Andamento', 'Artichokes - Jerusalem', 81.18, 67);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (172, 'Cancelado', 'Soup - Base Broth Beef', 50.55, 85);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (173, 'Cancelado', 'Tea - Mint', 15.85, 49);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (174, 'Em Andamento', 'Green Tea Refresher', 31.05, 27);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (175, 'Em Andamento', 'Island Oasis - Peach Daiquiri', 14.98, 27);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (176, 'Concluido', 'Capers - Pickled', 55.19, 31);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (177, 'Cancelado', 'Table Cloth 53x53 White', 13.73, 16);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (178, 'Cancelado', 'Fennel - Seeds', 14.13, 50);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (179, 'Concluido', 'Mushroom Morel Fresh', 52.07, 33);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (180, 'Cancelado', 'Fish - Scallops, Cold Smoked', 69.85, 34);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (181, 'Cancelado', 'Pork - Shoulder', 74.06, 37);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (182, 'Cancelado', 'Turnip - Mini', 94.65, 31);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (183, 'Cancelado', 'Vaccum Bag 10x13', 74.14, 8);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (184, 'Cancelado', 'Melon - Watermelon, Seedless', 66.3, 30);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (185, 'Concluido', 'Taro Root', 49.31, 91);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (186, 'Concluido', 'Bacardi Mojito', 38.73, 38);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (187, 'Concluido', 'Fennel', 58.33, 100);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (188, 'Concluido', 'Pepper - Sorrano', 23.17, 96);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (189, 'Cancelado', 'Filling - Mince Meat', 92.55, 7);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (190, 'Cancelado', 'Pasta - Canelloni', 10.88, 17);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (191, 'Concluido', 'Chocolate - Milk, Callets', 40.16, 86);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (192, 'Em Andamento', 'Honey - Comb', 13.81, 68);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (193, 'Em Andamento', 'Wine - Vineland Estate Semi - Dry', 10.86, 6);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (194, 'Concluido', 'Star Anise, Whole', 78.93, 53);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (195, 'Em Andamento', 'Yogurt - Assorted Pack', 57.56, 28);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (196, 'Cancelado', 'Milk - 2% 250 Ml', 48.64, 14);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (197, 'Cancelado', 'Carbonated Water - White Grape', 43.26, 75);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (198, 'Cancelado', 'Coconut Milk - Unsweetened', 40.41, 72);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (199, 'Cancelado', 'Appetizer - Sausage Rolls', 25.43, 95);
insert into Pedido (idPedido, status, descricao, frete, Cliente_idCliente) values (200, 'Em Andamento', 'Bread - Malt', 55.31, 74);
