insert into Produto (idProduto, categoria, descricao, valor) values (1, 'audio/x-mpeg-3', 'Sloe Gin - Mcguinness', 12.34);
insert into Produto (idProduto, categoria, descricao, valor) values (2, 'video/quicktime', 'Icecream Bar - Del Monte', 94.17);
insert into Produto (idProduto, categoria, descricao, valor) values (3, 'application/vnd.ms-powerpoint', 'Pastry - Cheese Baked Scones', 38.03);
insert into Produto (idProduto, categoria, descricao, valor) values (4, 'application/powerpoint', 'Tea - Herbal Sweet Dreams', 73.4);
insert into Produto (idProduto, categoria, descricao, valor) values (5, 'application/powerpoint', 'Lid Coffee Cup 8oz Blk', 84.91);
insert into Produto (idProduto, categoria, descricao, valor) values (6, 'image/x-tiff', 'Soup - Knorr, Chicken Gumbo', 9.32);
insert into Produto (idProduto, categoria, descricao, valor) values (7, 'application/powerpoint', 'Beef - Roasted, Cooked', 91.73);
insert into Produto (idProduto, categoria, descricao, valor) values (8, 'application/vnd.ms-excel', 'Chevere Logs', 54.87);
insert into Produto (idProduto, categoria, descricao, valor) values (9, 'image/gif', 'Bag - Bread, White, Plain', 7.88);
insert into Produto (idProduto, categoria, descricao, valor) values (10, 'video/x-msvideo', 'Muffin Mix - Banana Nut', 1.59);
insert into Produto (idProduto, categoria, descricao, valor) values (11, 'video/mpeg', 'Bread - Ciabatta Buns', 61.58);
insert into Produto (idProduto, categoria, descricao, valor) values (12, 'video/msvideo', 'Beer - Maudite', 19.67);
insert into Produto (idProduto, categoria, descricao, valor) values (13, 'application/x-troff-msvideo', 'Triple Sec - Mcguinness', 46.33);
insert into Produto (idProduto, categoria, descricao, valor) values (14, 'video/x-mpeg', 'Syrup - Monin - Granny Smith', 58.01);
insert into Produto (idProduto, categoria, descricao, valor) values (15, 'application/excel', 'Basil - Primerba, Paste', 31.31);
insert into Produto (idProduto, categoria, descricao, valor) values (16, 'application/pdf', 'Mcgillicuddy Vanilla Schnap', 6.15);
insert into Produto (idProduto, categoria, descricao, valor) values (17, 'image/jpeg', 'Liners - Baking Cups', 92.05);
insert into Produto (idProduto, categoria, descricao, valor) values (18, 'image/x-tiff', 'Lettuce - Boston Bib', 70.43);
insert into Produto (idProduto, categoria, descricao, valor) values (19, 'video/avi', 'Chicken - Whole Fryers', 27.05);
insert into Produto (idProduto, categoria, descricao, valor) values (20, 'application/excel', 'Rosemary - Fresh', 50.5);
