insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (1, 'Riffpath', '3553 Cardinal Park');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (2, 'Rhynoodle', '246 Glendale Center');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (3, 'Tavu', '8751 Messerschmidt Junction');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (4, 'Yakijo', '175 Bellgrove Junction');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (5, 'Shuffledrive', '773 Becker Drive');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (6, 'Omba', '6154 Waubesa Street');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (7, 'Aimbu', '18538 Fuller Street');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (8, 'Quimm', '5628 Brown Drive');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (9, 'Wordify', '35 Miller Hill');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (10, 'Edgetag', '35 Delladonna Hill');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (11, 'Aimbo', '18 American Ash Avenue');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (12, 'Zoombeat', '4 Sycamore Parkway');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (13, 'Buzzshare', '1986 Claremont Place');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (14, 'Avaveo', '24103 Judy Alley');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (15, 'Dabfeed', '4396 Thierer Way');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (16, 'Centidel', '39887 Mallory Terrace');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (17, 'Centizu', '91049 Colorado Way');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (18, 'Bubblebox', '1 3rd Pass');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (19, 'Jamia', '94 Lakewood Gardens Hill');
insert into Terceiro_Vendedor (idTerceiro_Vendedor, razao_social, local) values (20, 'Mudo', '57 Browning Drive');
