insert into Mecanico (idMecanico, nome, endereco, especialidade) values (1, 'Riva Packwood', '0 Sheridan Street', 'Mecânico de Manutenção Geral');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (2, 'Jackie MacShane', '35 Gina Drive', 'Mecânico especializado em carros antigos');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (3, 'Noe Luparti', '52691 Thompson Hill', 'Reparador de câmbios automáticos');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (4, 'Gaelan Joisce', '6 Division Circle', 'Mecânico especializado em carros antigos');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (5, 'Loy Cousen', '0669 Nevada Hill', 'Mecânico de Manutenção Geral');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (6, 'Misty Douberday', '5384 American Plaza', 'Reparador de câmbios automáticos');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (7, 'Reeba Shotton', '39609 Toban Terrace', 'Funileiro');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (8, 'Codee Kurten', '7 Packers Parkway', 'Funileiro');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (9, 'Leilah De Angelo', '53026 Farwell Hill', 'Mecânico de carros híbridos e elétricos');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (10, 'Kit Laden', '997 Harper Plaza', 'Mecânico especializado em carros antigos');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (11, 'Louisette McLice', '6632 Marquette Way', 'Funileiro');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (12, 'Nicolas Speakman', '2 Tennyson Point', 'Reparador de câmbios automáticos');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (13, 'Carey Ubsdall', '91828 Golf View Street', 'Mecânico de Manutenção Geral');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (14, 'Brocky Fasham', '11 Northport Parkway', 'Mecânico de Manutenção Geral');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (15, 'Rubina Dawks', '1 Moose Alley', 'Mecânico de carros híbridos e elétricos');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (16, 'Ronni Patise', '7 Dorton Way', 'Reparador de câmbios automáticos');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (17, 'Farlie Basil', '80658 Kings Center', 'Funileiro');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (18, 'Nil Wooller', '319 Talisman Street', 'Reparador de câmbios automáticos');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (19, 'Kayla Mulvey', '7 Brickson Park Center', 'Mecânico de Manutenção Geral');
insert into Mecanico (idMecanico, nome, endereco, especialidade) values (20, 'Brade Flaherty', '03465 Pepper Wood Street', 'Reparador de câmbios automáticos');
