insert into Peca (idPeca, nome, valor) values (1, 'Amortecedor da suspensão', 4768.13);
insert into Peca (idPeca, nome, valor) values (2, 'Anel de pistão', 6370.62);
insert into Peca (idPeca, nome, valor) values (3, 'Bomba elétrica de combustível', 53.4);
insert into Peca (idPeca, nome, valor) values (4, 'Bronzina', 2701.96);
insert into Peca (idPeca, nome, valor) values (5, 'Buzina ou equipamento similar', 4961.02);
insert into Peca (idPeca, nome, valor) values (6, 'Lâmpada para veículos automotivos', 4856.71);
insert into Peca (idPeca, nome, valor) values (7, 'Pino e anel de trava (retenção)', 1682.29);
insert into Peca (idPeca, nome, valor) values (8, 'Pistão de liga leve de alumínio', 4107.23);
insert into Peca (idPeca, nome, valor) values (9, 'Baterias', 6720.38);
insert into Peca (idPeca, nome, valor) values (10, 'Terminal de direção', 1162.32);
insert into Peca (idPeca, nome, valor) values (11, 'Barra de direção', 4615.64);
insert into Peca (idPeca, nome, valor) values (12, 'Barra de ligação', 4334.12);
insert into Peca (idPeca, nome, valor) values (13, 'Terminal axial', 4078.19);
insert into Peca (idPeca, nome, valor) values (14, 'Materiais de atrito para freios', 2345.81);
insert into Peca (idPeca, nome, valor) values (15, 'Rodas automotivas', 5371.22);
insert into Peca (idPeca, nome, valor) values (16, 'Vidro de segurança laminado de para-brisas', 5475.31);
insert into Peca (idPeca, nome, valor) values (17, 'Vidro de segurança temperado', 4850.62);
insert into Peca (idPeca, nome, valor) values (18, 'Fluído de freio', 6784.99);
insert into Peca (idPeca, nome, valor) values (19, 'Catalisador', 3578.35);
insert into Peca (idPeca, nome, valor) values (20, 'Motor', 7000.00);
