insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (1, 'Volkswagen', 'Passat', 1992, 'TGT-5636', 'Maroon', 17);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (2, 'Ford', 'F-Series', 1994, 'UEV-3494', 'Blue', 121);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (3, 'Toyota', 'Yaris', 2011, 'AEZ-0617', 'Purple', 68);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (4, 'Bentley', 'Azure', 2010, 'EJV-9787', 'Yellow', 130);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (5, 'Audi', 'S4', 2006, 'CSG-2325', 'Khaki', 118);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (6, 'Maserati', '228', 1989, 'PBZ-5238', 'Maroon', 8);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (7, 'Isuzu', 'Rodeo', 2003, 'UGG-4862', 'Green', 10);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (8, 'Ford', 'Explorer', 2001, 'VWQ-5848', 'Maroon', 170);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (9, 'Maserati', 'Quattroporte', 2010, 'DYO-6214', 'Crimson', 50);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (10, 'Pontiac', 'Grand Prix Turbo', 1990, 'OFW-5323', 'Mauv', 142);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (11, 'GMC', 'Yukon XL 2500', 2012, 'WDT-2016', 'Orange', 182);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (12, 'Ford', 'Expedition', 2003, 'KRL-7047', 'Violet', 127);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (13, 'Maybach', '57', 2008, 'HVX-2583', 'Fuscia', 150);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (14, 'Saab', '9000', 1989, 'ONL-7429', 'Fuscia', 98);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (15, 'Cadillac', 'Seville', 2000, 'DQK-1512', 'Green', 71);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (16, 'Lamborghini', 'Countach', 1989, 'NLG-1498', 'Maroon', 58);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (17, 'Hyundai', 'Sonata', 2002, 'OZF-4514', 'Pink', 59);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (18, 'Mitsubishi', 'Pajero', 1990, 'ERU-4339', 'Blue', 64);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (19, 'GMC', 'Sonoma', 1998, 'SCI-4194', 'Blue', 135);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (20, 'Mitsubishi', 'Truck', 1993, 'IYK-9865', 'Yellow', 39);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (21, 'Bentley', 'Continental GTC', 2008, 'GZZ-1071', 'Crimson', 62);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (22, 'Isuzu', 'Trooper', 1997, 'TWN-1787', 'Crimson', 197);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (23, 'Ford', 'F250', 1984, 'JZH-5030', 'Aquamarine', 32);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (24, 'Cadillac', 'DeVille', 2004, 'VAP-3904', 'Khaki', 191);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (25, 'Mitsubishi', 'Montero', 1994, 'WXZ-1528', 'Mauv', 35);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (26, 'Chevrolet', 'Express 3500', 2011, 'OOD-3266', 'Teal', 20);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (27, 'Porsche', '911', 2008, 'APP-8682', 'Indigo', 18);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (28, 'BMW', 'X3', 2010, 'FBT-3860', 'Yellow', 191);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (29, 'GMC', 'Savana', 2006, 'FUR-6074', 'Maroon', 117);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (30, 'Pontiac', 'Grand Am', 1997, 'UNT-5981', 'Fuscia', 69);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (31, 'Subaru', 'Brat', 1987, 'BQG-4963', 'Goldenrod', 146);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (32, 'Volkswagen', 'Eos', 2009, 'GGX-9274', 'Red', 105);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (33, 'Dodge', 'Intrepid', 2002, 'MNF-0782', 'Pink', 74);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (34, 'Jeep', 'Wrangler', 2010, 'JMT-9648', 'Teal', 47);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (35, 'Mercedes-Benz', 'SL-Class', 1987, 'WVG-6238', 'Goldenrod', 50);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (36, 'Chevrolet', 'Express 3500', 2010, 'FDA-3840', 'Goldenrod', 194);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (37, 'Audi', 'Allroad', 2004, 'XYH-4903', 'Pink', 96);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (38, 'Ford', 'Ranger', 1985, 'LLN-5756', 'Pink', 193);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (39, 'Ford', 'Mustang', 2012, 'RRE-9174', 'Mauv', 84);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (40, 'Dodge', 'Ram 1500 Club', 1996, 'WAT-8556', 'Aquamarine', 101);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (41, 'Toyota', 'Previa', 1994, 'WKU-7923', 'Fuscia', 124);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (42, 'Ford', 'ZX2', 2003, 'UPK-2153', 'Blue', 200);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (43, 'GMC', 'Suburban 1500', 1993, 'SLO-5670', 'Teal', 139);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (44, 'Lexus', 'LS Hybrid', 2010, 'RCC-7387', 'Puce', 101);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (45, 'Dodge', 'Dakota', 2010, 'NWX-6931', 'Purple', 160);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (46, 'Mercury', 'Mariner', 2008, 'RDX-6494', 'Aquamarine', 29);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (47, 'Toyota', '4Runner', 1993, 'YOB-5234', 'Teal', 157);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (48, 'Chevrolet', 'Suburban 1500', 2002, 'AQA-6735', 'Aquamarine', 72);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (49, 'Aston Martin', 'Vantage', 2009, 'MPY-9138', 'Blue', 80);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (50, 'Porsche', '928', 1991, 'MBU-8521', 'Mauv', 2);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (51, 'Kia', 'Sportage', 2001, 'MCO-9176', 'Green', 161);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (52, 'Ford', 'Galaxie', 1966, 'UKZ-1829', 'Violet', 170);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (53, 'Mitsubishi', 'Montero', 1992, 'GOH-8576', 'Pink', 125);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (54, 'Ford', 'Ranger', 2010, 'EXZ-4342', 'Indigo', 22);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (55, 'Nissan', 'GT-R', 2013, 'MMI-0685', 'Violet', 61);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (56, 'Lotus', 'Esprit', 2001, 'VIH-5724', 'Turquoise', 18);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (57, 'Mercury', 'Tracer', 1988, 'VLB-0224', 'Aquamarine', 37);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (58, 'Land Rover', 'LR2', 2008, 'TFM-3151', 'Pink', 74);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (59, 'Dodge', 'Neon', 1999, 'XCO-1917', 'Green', 182);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (60, 'Chevrolet', 'Metro', 2000, 'AKU-8139', 'Puce', 120);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (61, 'Dodge', 'Ram 2500', 2002, 'SGO-7145', 'Red', 164);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (62, 'Toyota', 'Corolla', 2004, 'BRR-0705', 'Indigo', 17);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (63, 'Dodge', 'Avenger', 2010, 'EEG-3601', 'Puce', 90);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (64, 'Chrysler', '300M', 2002, 'GSC-2311', 'Blue', 118);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (65, 'Jeep', 'Grand Cherokee', 1996, 'XWO-7792', 'Green', 112);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (66, 'Chevrolet', 'Cavalier', 2000, 'CRD-7468', 'Puce', 97);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (67, 'Jeep', 'Cherokee', 1996, 'UBF-1962', 'Fuscia', 196);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (68, 'Ford', 'F450', 2011, 'JVA-2885', 'Purple', 77);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (69, 'Dodge', 'Durango', 2009, 'KGU-9992', 'Blue', 135);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (70, 'Mercedes-Benz', 'SL-Class', 1990, 'XHV-0064', 'Purple', 2);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (71, 'Ford', 'Mustang', 1995, 'YFW-7424', 'Goldenrod', 172);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (72, 'Oldsmobile', 'LSS', 1997, 'ARC-0353', 'Teal', 196);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (73, 'BMW', '6 Series', 2010, 'FGZ-9819', 'Khaki', 101);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (74, 'Chevrolet', 'HHR Panel', 2006, 'WWE-9820', 'Orange', 48);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (75, 'Lotus', 'Elise', 2005, 'TTI-0460', 'Teal', 187);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (76, 'Mercury', 'Mariner', 2010, 'QJU-2458', 'Mauv', 29);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (77, 'Toyota', 'Tacoma', 2001, 'FMC-5546', 'Crimson', 86);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (78, 'BMW', '1 Series', 2008, 'DNC-2151', 'Fuscia', 41);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (79, 'Chevrolet', 'Silverado', 2011, 'HBM-0203', 'Crimson', 158);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (80, 'Lincoln', 'Navigator', 2012, 'BNA-3790', 'Puce', 117);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (81, 'Oldsmobile', 'Achieva', 1994, 'UQD-3262', 'Orange', 42);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (82, 'Chevrolet', 'Prizm', 1998, 'PKN-4140', 'Yellow', 132);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (83, 'Acura', 'NSX', 2002, 'AJP-2980', 'Green', 115);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (84, 'Ford', 'Escape', 2009, 'VOU-4728', 'Goldenrod', 37);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (85, 'Chevrolet', 'Suburban', 2010, 'TRZ-1007', 'Fuscia', 183);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (86, 'Ford', 'Festiva', 1992, 'WXD-2622', 'Green', 2);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (87, 'Dodge', 'Ram 2500', 2001, 'IER-2184', 'Indigo', 89);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (88, 'BMW', 'M3', 2005, 'YVW-7021', 'Crimson', 10);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (89, 'Dodge', 'Charger', 2008, 'GIE-6486', 'Yellow', 147);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (90, 'Ford', 'Aerostar', 1992, 'VIR-5382', 'Orange', 98);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (91, 'Suzuki', 'Vitara', 2000, 'RCI-1076', 'Purple', 155);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (92, 'Mercury', 'Monterey', 2007, 'OJV-5033', 'Puce', 188);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (93, 'Lincoln', 'LS', 2003, 'KFT-3530', 'Yellow', 96);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (94, 'Mazda', 'MX-5', 1992, 'LFC-3915', 'Mauv', 6);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (95, 'Mercedes-Benz', '500SEC', 1993, 'ZQN-4170', 'Crimson', 28);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (96, 'Chevrolet', '2500', 1995, 'LJB-5910', 'Orange', 22);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (97, 'Cadillac', 'STS-V', 2009, 'MCZ-1937', 'Pink', 43);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (98, 'Chevrolet', 'Express 1500', 2008, 'SWK-0906', 'Violet', 176);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (99, 'Saturn', 'S-Series', 1997, 'UQZ-6146', 'Maroon', 24);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (100, 'Ford', 'Escort', 1993, 'KHH-4865', 'Green', 23);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (101, 'Buick', 'Coachbuilder', 1993, 'BZM-3704', 'Mauv', 48);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (102, 'Chrysler', '300M', 2001, 'NXI-7509', 'Pink', 38);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (103, 'Ford', 'Focus', 2000, 'HWX-1429', 'Maroon', 55);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (104, 'Nissan', 'Quest', 2005, 'DLO-8902', 'Aquamarine', 72);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (105, 'Volvo', 'XC70', 2003, 'CRV-9216', 'Yellow', 37);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (106, 'Kia', 'Sorento', 2003, 'KFG-4685', 'Violet', 171);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (107, 'Volvo', '850', 1997, 'MSO-8176', 'Orange', 26);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (108, 'Chrysler', '300M', 2004, 'FJT-5334', 'Red', 107);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (109, 'Mitsubishi', 'Lancer', 2012, 'JJG-2819', 'Red', 161);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (110, 'Dodge', 'Ram Van B350', 1993, 'JGD-6711', 'Yellow', 153);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (111, 'Volkswagen', 'Golf III', 1995, 'RVK-6127', 'Crimson', 140);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (112, 'Scion', 'xB', 2004, 'TZE-5580', 'Yellow', 193);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (113, 'GMC', 'Rally Wagon 2500', 1993, 'OUF-0662', 'Turquoise', 159);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (114, 'Chevrolet', '1500', 1995, 'IYW-2441', 'Mauv', 189);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (115, 'Jeep', 'Compass', 2009, 'VLE-1289', 'Khaki', 191);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (116, 'Nissan', 'Versa', 2010, 'WHR-2887', 'Fuscia', 104);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (117, 'Dodge', 'Challenger', 2011, 'GDQ-6264', 'Crimson', 96);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (118, 'BMW', '7 Series', 1998, 'GTW-9590', 'Yellow', 153);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (119, 'Volkswagen', 'Fox', 1990, 'GMI-2282', 'Turquoise', 73);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (120, 'Land Rover', 'Range Rover', 2010, 'HLS-0950', 'Indigo', 198);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (121, 'Toyota', 'Camry', 2003, 'UWE-1746', 'Indigo', 61);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (122, 'Saturn', 'Aura', 2007, 'PYW-6056', 'Khaki', 84);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (123, 'Ford', 'Explorer Sport Trac', 2009, 'HRR-2938', 'Purple', 75);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (124, 'Volvo', 'V40', 2002, 'ECQ-4235', 'Orange', 165);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (125, 'Audi', 'A6', 2007, 'TPZ-6326', 'Yellow', 148);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (126, 'Porsche', 'Cayenne', 2009, 'PSX-7078', 'Purple', 182);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (127, 'Suzuki', 'Kizashi', 2011, 'OGG-4954', 'Blue', 117);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (128, 'Lexus', 'ES', 2002, 'ZLK-1926', 'Aquamarine', 19);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (129, 'Suzuki', 'Esteem', 2001, 'DJC-5323', 'Green', 158);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (130, 'Mitsubishi', 'Galant', 2009, 'QNC-4224', 'Mauv', 156);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (131, 'Land Rover', 'Range Rover Sport', 2011, 'TBU-6727', 'Teal', 145);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (132, 'Toyota', '4Runner', 2009, 'HCN-8264', 'Teal', 70);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (133, 'Volvo', 'S60', 2008, 'IAR-9681', 'Maroon', 115);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (134, 'Nissan', 'Pathfinder', 2004, 'UPH-7559', 'Crimson', 135);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (135, 'Toyota', 'Tacoma', 1998, 'AJW-6467', 'Maroon', 99);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (136, 'Acura', 'Legend', 1989, 'QBG-2595', 'Maroon', 10);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (137, 'Mazda', 'Mazda6', 2004, 'LHQ-6972', 'Purple', 132);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (138, 'Kia', 'Sedona', 2006, 'CJF-7738', 'Indigo', 80);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (139, 'Mitsubishi', 'Endeavor', 2011, 'GDR-0147', 'Blue', 116);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (140, 'Volkswagen', 'Golf', 2012, 'ERY-2069', 'Turquoise', 183);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (141, 'Isuzu', 'Trooper', 1993, 'LLW-4093', 'Puce', 35);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (142, 'Honda', 'Element', 2010, 'TTX-3296', 'Yellow', 190);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (143, 'Porsche', '911', 1988, 'ERZ-2899', 'Pink', 79);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (144, 'Land Rover', 'Range Rover Sport', 2008, 'JUC-6353', 'Orange', 117);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (145, 'Ford', 'F150', 1993, 'PHU-5476', 'Puce', 75);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (146, 'Mercury', 'Montego', 2005, 'EAE-8117', 'Maroon', 113);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (147, 'Kia', 'Rio', 2008, 'CRX-1137', 'Blue', 9);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (148, 'Honda', 'Accord', 1997, 'XPB-8663', 'Pink', 17);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (149, 'Ford', 'E250', 2009, 'MCX-9187', 'Violet', 114);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (150, 'Mazda', 'Mazdaspeed 3', 2008, 'ZHI-3540', 'Puce', 69);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (151, 'Chevrolet', 'Tracker', 2001, 'DWB-7384', 'Khaki', 63);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (152, 'Jaguar', 'XK', 2006, 'DBR-2557', 'Red', 51);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (153, 'BMW', 'X5', 2008, 'COB-8978', 'Maroon', 167);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (154, 'Jeep', 'Liberty', 2009, 'KFE-0353', 'Aquamarine', 46);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (155, 'Dodge', 'Ram Van 3500', 1995, 'PZH-1686', 'Pink', 193);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (156, 'Toyota', 'Supra', 1997, 'QWB-1482', 'Green', 92);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (157, 'Chevrolet', 'Express 2500', 2008, 'XKI-5925', 'Pink', 163);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (158, 'Isuzu', 'Ascender', 2003, 'FGT-6337', 'Khaki', 165);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (159, 'Chevrolet', 'Caprice', 1991, 'RDV-8139', 'Blue', 14);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (160, 'BMW', '5 Series', 2002, 'XJM-2419', 'Indigo', 159);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (161, 'GMC', 'Terrain', 2010, 'PIV-6527', 'Khaki', 15);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (162, 'Maserati', 'Quattroporte', 2010, 'FOC-8244', 'Red', 167);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (163, 'Mazda', '626', 2001, 'ENA-9395', 'Orange', 195);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (164, 'Chevrolet', 'S10', 1996, 'UPW-4020', 'Red', 13);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (165, 'Audi', 'A6', 2005, 'JJA-7137', 'Mauv', 17);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (166, 'Toyota', 'T100', 1995, 'ZVA-5804', 'Turquoise', 59);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (167, 'Ram', 'C/V', 2012, 'ZDS-7650', 'Goldenrod', 145);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (168, 'Chevrolet', 'Express 2500', 2007, 'UVF-8130', 'Teal', 66);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (169, 'Chevrolet', 'Tahoe', 2000, 'WUJ-5148', 'Teal', 159);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (170, 'Mitsubishi', 'Montero Sport', 1999, 'LXG-7181', 'Goldenrod', 7);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (171, 'Volkswagen', 'New Beetle', 2001, 'RDL-8270', 'Khaki', 16);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (172, 'Pontiac', 'Grand Prix', 1963, 'JOR-1748', 'Fuscia', 24);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (173, 'Jaguar', 'XK Series', 1999, 'GKH-1288', 'Indigo', 127);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (174, 'Chevrolet', 'Traverse', 2009, 'YEX-4627', 'Maroon', 117);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (175, 'Rolls-Royce', 'Phantom', 2007, 'WWN-9999', 'Aquamarine', 105);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (176, 'Toyota', 'Avalon', 2009, 'ZAN-5154', 'Green', 119);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (177, 'BMW', '1 Series', 2011, 'GEW-2827', 'Crimson', 39);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (178, 'Jeep', 'Grand Cherokee', 2012, 'XGJ-5552', 'Red', 35);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (179, 'Pontiac', '6000', 1988, 'GFQ-3941', 'Turquoise', 38);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (180, 'Mercedes-Benz', 'SL-Class', 1992, 'ZSZ-1203', 'Orange', 82);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (181, 'BMW', '8 Series', 1997, 'PSU-0551', 'Indigo', 100);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (182, 'Suzuki', 'Vitara', 2001, 'WLC-7123', 'Violet', 54);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (183, 'Mazda', 'B-Series', 2004, 'EZW-7665', 'Violet', 54);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (184, 'Mazda', 'Miata MX-5', 1994, 'OWZ-8713', 'Fuscia', 152);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (185, 'Ford', 'E150', 2008, 'ZGO-9705', 'Teal', 183);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (186, 'Land Rover', 'Freelander', 2010, 'VIY-7750', 'Crimson', 21);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (187, 'Ford', 'Excursion', 2000, 'MIC-5114', 'Teal', 98);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (188, 'Lincoln', 'Continental', 1994, 'LIJ-3706', 'Turquoise', 10);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (189, 'Volkswagen', 'Golf', 2001, 'PRM-8217', 'Mauv', 197);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (190, 'Buick', 'Regal', 1997, 'NKX-9631', 'Violet', 7);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (191, 'Chevrolet', '3500', 1996, 'TET-1533', 'Khaki', 65);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (192, 'Volkswagen', 'Fox', 1987, 'FDR-3315', 'Puce', 137);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (193, 'GMC', 'Sierra 2500', 2002, 'PTS-4519', 'Violet', 77);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (194, 'Chevrolet', 'Avalanche', 2007, 'YDT-0905', 'Mauv', 25);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (195, 'Ford', 'Transit Connect', 2010, 'PFF-5078', 'Blue', 5);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (196, 'Subaru', 'Tribeca', 2012, 'RXI-4619', 'Puce', 99);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (197, 'Suzuki', 'XL-7', 2007, 'GNQ-0181', 'Puce', 179);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (198, 'Suzuki', 'XL-7', 2008, 'YJD-0679', 'Mauv', 172);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (199, 'Jeep', 'Liberty', 2005, 'MVS-8212', 'Goldenrod', 19);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (200, 'Toyota', 'Tacoma', 2011, 'DGS-2187', 'Pink', 53);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (201, 'Volkswagen', 'Touareg 2', 2008, 'WKH-9860', 'Maroon', 44);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (202, 'Lotus', 'Esprit Turbo', 1984, 'WHI-2542', 'Pink', 63);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (203, 'Mercedes-Benz', '300SL', 1993, 'FLW-6536', 'Yellow', 156);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (204, 'Volkswagen', 'Eos', 2009, 'VEH-2816', 'Puce', 194);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (205, 'Mitsubishi', 'RVR', 1992, 'ZKO-8919', 'Mauv', 156);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (206, 'Dodge', 'Viper RT/10', 1994, 'IQH-7808', 'Mauv', 93);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (207, 'Chrysler', 'Voyager', 2001, 'GMX-8113', 'Maroon', 120);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (208, 'Dodge', 'Dynasty', 1992, 'RVC-3073', 'Fuscia', 101);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (209, 'Bentley', 'Continental Flying Spur', 2009, 'VIM-4574', 'Purple', 180);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (210, 'Toyota', 'Corolla', 2000, 'UEI-8242', 'Aquamarine', 71);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (211, 'Acura', 'ZDX', 2010, 'SHV-7373', 'Yellow', 61);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (212, 'Dodge', 'Ram 2500', 2000, 'WJZ-7092', 'Indigo', 57);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (213, 'Ford', 'Transit Connect', 2010, 'CXW-6674', 'Orange', 82);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (214, 'Saab', '9-2X', 2005, 'DCY-8970', 'Purple', 57);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (215, 'Chrysler', 'LeBaron', 1993, 'EUA-0574', 'Mauv', 62);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (216, 'Audi', 'V8', 1990, 'OCT-4630', 'Blue', 159);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (217, 'Cadillac', 'DeVille', 2000, 'TMY-2828', 'Aquamarine', 51);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (218, 'Mercedes-Benz', 'E-Class', 1995, 'YCQ-2200', 'Crimson', 138);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (219, 'Toyota', 'Avalon', 2003, 'EBY-0956', 'Fuscia', 98);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (220, 'Chevrolet', 'Malibu', 2003, 'SDK-5155', 'Green', 98);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (221, 'Jaguar', 'X-Type', 2005, 'UBY-5765', 'Violet', 166);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (222, 'Mitsubishi', 'Mirage', 1997, 'RWP-5336', 'Violet', 157);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (223, 'Mercedes-Benz', 'SL-Class', 2007, 'XOP-8208', 'Fuscia', 193);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (224, 'Dodge', 'Ram 1500', 1996, 'MIM-7140', 'Pink', 67);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (225, 'GMC', 'Rally Wagon 2500', 1994, 'CMB-4957', 'Maroon', 83);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (226, 'Honda', 'Civic GX', 2003, 'NAG-2935', 'Fuscia', 105);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (227, 'Chevrolet', 'G-Series 1500', 1998, 'PQE-0738', 'Blue', 93);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (228, 'Subaru', 'Legacy', 1996, 'HDA-7367', 'Yellow', 47);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (229, 'Mazda', 'Mazdaspeed 3', 2012, 'VUK-0105', 'Turquoise', 96);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (230, 'Mercury', 'Lynx', 1985, 'NBO-7526', 'Puce', 46);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (231, 'Mercedes-Benz', 'SLK-Class', 2006, 'UJN-4011', 'Goldenrod', 37);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (232, 'Ford', 'Econoline E350', 1996, 'XTX-0027', 'Yellow', 2);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (233, 'Eagle', 'Premier', 1992, 'QHD-3887', 'Khaki', 97);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (234, 'Honda', 'Prelude', 1993, 'USL-7828', 'Fuscia', 172);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (235, 'Chevrolet', '2500', 1999, 'KRJ-8688', 'Fuscia', 64);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (236, 'Ford', 'Thunderbird', 1985, 'AWD-5906', 'Crimson', 33);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (237, 'Ford', 'Edge', 2008, 'DGI-9054', 'Puce', 18);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (238, 'Honda', 'CR-V', 2002, 'GSE-4302', 'Pink', 23);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (239, 'Saab', '9-5', 2007, 'DTP-6589', 'Goldenrod', 91);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (240, 'GMC', 'Sierra', 2008, 'YQX-7351', 'Yellow', 131);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (241, 'Toyota', 'Paseo', 1995, 'KUW-4195', 'Khaki', 165);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (242, 'Toyota', '4Runner', 2008, 'LKR-1321', 'Yellow', 26);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (243, 'BMW', 'Alpina B7', 2008, 'QUN-3911', 'Blue', 154);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (244, 'Nissan', 'Murano', 2006, 'EIX-2794', 'Violet', 145);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (245, 'GMC', 'Savana 2500', 2001, 'NVX-9087', 'Purple', 10);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (246, 'Dodge', 'Ram 3500', 1996, 'COT-2042', 'Mauv', 156);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (247, 'Ford', 'Bronco', 1986, 'NMU-1098', 'Violet', 145);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (248, 'Dodge', 'Dakota', 1994, 'USD-2945', 'Red', 11);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (249, 'GMC', 'Sonoma Club Coupe', 1996, 'RBB-6703', 'Maroon', 36);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (250, 'Eagle', 'Talon', 1991, 'TPD-4715', 'Aquamarine', 129);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (251, 'Chevrolet', 'Suburban 2500', 2001, 'YWT-1705', 'Aquamarine', 48);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (252, 'Ford', 'Bronco', 1990, 'YWP-3694', 'Violet', 151);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (253, 'Dodge', 'Viper', 1994, 'CMR-0650', 'Yellow', 164);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (254, 'Hummer', 'H3', 2007, 'PLD-8090', 'Mauv', 113);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (255, 'Suzuki', 'Equator', 2011, 'CXQ-3232', 'Khaki', 123);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (256, 'GMC', 'Savana 1500', 1998, 'HLL-8286', 'Goldenrod', 174);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (257, 'Chevrolet', 'S10', 2001, 'DJA-1425', 'Mauv', 107);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (258, 'Chrysler', 'Concorde', 2003, 'RGI-6751', 'Blue', 190);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (259, 'Acura', 'TL', 2011, 'ZYM-8819', 'Fuscia', 21);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (260, 'BMW', 'X5', 2013, 'YCB-3060', 'Puce', 95);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (261, 'Jaguar', 'S-Type', 2004, 'ZIP-5885', 'Goldenrod', 132);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (262, 'Honda', 'Pilot', 2012, 'WNE-9880', 'Crimson', 180);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (263, 'Lotus', 'Evora', 2012, 'ULP-0092', 'Red', 61);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (264, 'Hyundai', 'Accent', 1998, 'UUA-4354', 'Pink', 107);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (265, 'Audi', 'S8', 2007, 'RZN-8120', 'Khaki', 172);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (266, 'Lincoln', 'Navigator L', 2012, 'URK-5840', 'Blue', 54);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (267, 'Chevrolet', 'HHR', 2007, 'SAS-2853', 'Violet', 63);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (268, 'Dodge', 'Daytona', 1992, 'PRF-8489', 'Red', 122);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (269, 'Porsche', 'Cayenne', 2004, 'YJK-9627', 'Crimson', 132);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (270, 'Mazda', 'Protege', 1993, 'WKZ-1815', 'Khaki', 94);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (271, 'Merkur', 'XR4Ti', 1985, 'JGI-8316', 'Puce', 169);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (272, 'Mercedes-Benz', 'C-Class', 2012, 'IKN-2113', 'Crimson', 42);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (273, 'Toyota', 'RAV4', 2004, 'FRD-7795', 'Fuscia', 147);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (274, 'BMW', '1 Series', 2011, 'AFI-4719', 'Crimson', 109);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (275, 'Hyundai', 'Accent', 2002, 'BQQ-9287', 'Orange', 20);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (276, 'Land Rover', 'Sterling', 1991, 'LCM-0276', 'Blue', 177);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (277, 'Lexus', 'RX', 2000, 'EQY-5564', 'Aquamarine', 6);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (278, 'Nissan', 'Leaf', 2011, 'UOC-8891', 'Green', 15);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (279, 'Volvo', 'S60', 2006, 'TDY-4681', 'Mauv', 53);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (280, 'Porsche', 'Panamera', 2013, 'JNC-0705', 'Turquoise', 11);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (281, 'Honda', 'Prelude', 2000, 'HFR-4071', 'Orange', 179);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (282, 'Maserati', 'Quattroporte', 2006, 'OSA-4853', 'Orange', 181);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (283, 'Volvo', 'V70', 2002, 'HCC-8897', 'Maroon', 98);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (284, 'Lotus', 'Elise', 2007, 'FZL-4701', 'Violet', 106);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (285, 'Volkswagen', 'Cabriolet', 1985, 'JRU-8166', 'Violet', 50);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (286, 'Pontiac', 'Grand Prix', 1993, 'MJD-0167', 'Green', 11);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (287, 'Nissan', 'Sentra', 1993, 'TQL-9603', 'Fuscia', 120);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (288, 'Lotus', 'Exige', 2005, 'JKZ-0817', 'Violet', 173);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (289, 'Chevrolet', 'Corvette', 2012, 'YVN-8032', 'Maroon', 118);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (290, 'Plymouth', 'Colt Vista', 1993, 'HBI-8534', 'Orange', 122);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (291, 'Jaguar', 'XJ', 2011, 'SLJ-1364', 'Turquoise', 164);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (292, 'Hummer', 'H3', 2008, 'HUN-6417', 'Yellow', 161);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (293, 'Porsche', 'Carrera GT', 2005, 'ZSY-4039', 'Green', 39);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (294, 'Chevrolet', 'Equinox', 2010, 'LLW-5834', 'Maroon', 131);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (295, 'Chrysler', 'Concorde', 1996, 'IVM-3390', 'Crimson', 15);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (296, 'Nissan', 'Pathfinder', 2010, 'SVN-5724', 'Violet', 127);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (297, 'Dodge', 'Ram Wagon B150', 1992, 'WTR-1921', 'Yellow', 172);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (298, 'Ford', 'E-Series', 2011, 'AVD-7849', 'Mauv', 143);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (299, 'Mitsubishi', 'Challenger', 1999, 'BJP-1887', 'Goldenrod', 9);
insert into Veiculo (idVeiculo, marca, modelo, ano, placa, cor, Cliente_idCliente) values (300, 'Lincoln', 'MKT', 2010, 'UMZ-2759', 'Fuscia', 145);
